### ISSUE TITLE
Custom-ui not working on HA 0.93.0

### ISSUE THREAD

**Issue by sendorm** [andrey-git/home-assistant-custom-ui#172]
### Checklist
- [X] I'm running the latest version of CustomUI ([Update guide](https://github.com/andrey-git/home-assistant-custom-ui/blob/master/docs/installing.md#updating)) or using a specific [release](https://github.com/andrey-git/home-assistant-custom-ui/releases) that is not marked as "Broken".
- [X] I tried to force-refresh (Ctrl+Shift+R / Ctrl+F5) the browser
- [X] (Optional, but recommended) I'm using Chrome or tried to reproduce the feature on Chrome.

**Browser + Version:** Opera 60.0.

**CustomUI version:** Release 2019-03-24

**Home Assistant release (`hass --version`):** 0.93.0

The custom-ui just disappeared from HASS after updating to 0.93.0.

**Comment by timfosse** [comment]
Same problem here

**Comment by stepanov1975** [comment]
Same problem

**Comment by Mariusthvdb** [comment]
Haven’t updated yet because feared this could related? https://github.com/home-assistant/home-assistant/pull/23618

**Comment by sendorm** [comment]
@Mariusthvdb I also think that the problem is related to js detection breaking change. Suprisingly custom-ui still works fine with ios.

**Comment by timfosse** [comment]
> @Mariusthvdb I also think that the problem is related to js detection breaking change. Suprisingly custom-ui still works fine with ios.

Also works in my iOS app!

**Comment by Mariusthvdb** [comment]
you might be lucky using option 1.1?
https://github.com/andrey-git/home-assistant-custom-ui/blob/master/docs/activating.md

using:

```
customizer:
  custom_ui: local
```

please try, and let us know?

**Comment by rccoleman** [comment]
I'm seeing the same thing - works in the iOS app, doesn't work in a browser on the desktop - and I just "converted" to 1.1 with no change in behavior.  I had additional extra_ lines in frontend: and commented them out.

**Comment by sendorm** [comment]
Yes I am already on option 1.1. Tested it on lovelace only. Works on ios but not on any desktop browser. 
I remember, setting the  

```
frontend:
  javascript_version: latest
```

to make custom-ui work long time ago (pre 0.88 probably not sure)
This option is no longer available in HA.

**Comment by Mariusthvdb** [comment]
so is this it?  Regular/Legacy HA got killed in 1 strike, without any fair notice or discussion? And why even, why not let people still using regular HA have their Instance use these extra_html extensions? at least for some transition time.
there are few more cards that won't work now, not only custom-ui is heavily used.
Cant believe this is happening....

**Comment by sendorm** [comment]
I am pretty sure @andrey-git will find a solution to this. Fingers crossed. Don’t lose your hopes yet :)

**Comment by Mariusthvdb** [comment]
hope so too, though he hasn't been around for quite some time... also,  not only custom-ui will be affected, but several other heavily uses custom cards in HA. Tiles, weather cards, to name but a few, that are loaded via frontend...

**Comment by andrey-git** [comment]
I released new CustomUI version 2019-05-18.
Everything seems to work in Chrome.

Note that since backend-detection of modern-vs-old was dropped - you can no longer use my CustomUI (or any Polymer based custom ui for that matter) on *both* new and old browsers.

**Comment by JAAlperin** [comment]
andrey-git

Thanks for the new release.

Two questions, please:
You've marked it for 94+.  Did you mean 93+, or is there a 94b coming?
You say "can no longer use my CustomUI on both new and old browsers."  Do you mean it can be used on one or the other, or that it cannot be used at all?

**Comment by sendorm** [comment]
Tested on opera browser. Everything works fine, thank you @andrey-git .

**Comment by networkpotato** [comment]
Replaced the two files in www/custom-ui with the new ones, still not working. And now it stopped working on iOS too....

**Comment by rccoleman** [comment]
Try running the included update.sh. Working for me in 0.93.1.

**Comment by x99percent** [comment]
Working for me in Chrome on Windows, but not on Android.  

EDIT: Updating to 0.94.x fixed mobile.

**Comment by Mariusthvdb** [comment]
just updated to 94.3, but don't see anything not working just yet, and havent upgraded the custom-ui...

what exactly was causing issues, needing an update to the custom-ui?
